export default {
    posts: [
        {title:"오버사이즈 스트라이프 셔츠", src: "~/assets/images/test.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test.jpeg"},
        {title:"head", src: "~/assets/images/test.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test.jpeg"},
        {title:"head", src: "~/assets/images/test.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test2.jpeg"},
        {title:"head", src: "~/assets/images/test.jpeg"},
    ],
    tags: [
            {name: "청바지", type: "cloth"},
            {name: "티셔츠", type: "cloth"},
            {name: "코트", type: "cloth"},
            {name: "슬랙스", type: "cloth"},
            {name: "후드코트", type: "cloth"},
            {name: "ma-1", type: "cloth"},
            {name: "맨투맨", type: "cloth"},
            {name: "옥스퍼드 구두", type: "cloth"},
            {name: "가죽자켓", type: "cloth"},
            {name: "베스트", type: "cloth"},
            {name: "후리스", type: "cloth"},
            {name: "캐쥬얼", type: "style"},
            {name: "밀리터리", type: "style"},
            {name: "오피스", type: "style"},
            {name: "걸리쉬", type: "style"},
            {name: "템포러리", type: "style"},
            {name: "포멀", type: "style"}
    ],
    peedmanager: 1,
    abmanager: true
}
