export default {
    REQUEST: 'requestpost',
    GETPOST: 'getpost',
    CLEANPOST: 'cleanpost',
    PEEDCH: 'peedch',
    SDP_V: 'setdetailpagedata_version',
    SDP: 'setdetailpagedata', //Set Detail Page
    RSDP: 'resetdetailpagedata',
    CL: 'clicklike',
    WC: 'writecomment',
    STD: 'settagdata',
    SETD: 'sendtagdata',
    GSP: 'getsellingproduct',
    SAP: 'setapipath',
    SEI: 'seteventinfo',
    RT: 'researchtag',
    PSLC: 'postsortlikecount',
    PSD: 'postsortdate',
    GMP: 'getmypost',
    GML: 'getmylike',
    DCL: 'detailpageclicklike',
    CC: 'checkcomment',
}
